const { contextBridge, ipcRenderer } = require('electron')

contextBridge.exposeInMainWorld('lolCoach', {
  onGameData:       (cb) => ipcRenderer.on('game-data', (_, data) => cb(data)),
  onGameNotRunning: (cb) => ipcRenderer.on('game-not-running', () => cb()),
  onSetTtsMuted:    (cb) => ipcRenderer.on('set-tts-muted', (_, m) => cb(m)),
  notifyTtsMuted:   (m)  => ipcRenderer.send('set-tts-state', m),
  closeWindow:      () => ipcRenderer.send('close-window'),
  minimizeWindow:   () => ipcRenderer.send('minimize-window'),
  hasApiKey:        () => ipcRenderer.invoke('has-api-key'),
  saveApiKey:       (key) => ipcRenderer.invoke('save-api-key', key),
  aiCoaching:       (prompt) => ipcRenderer.invoke('ai-coaching', prompt),
  aiGameStart:      (prompt) => ipcRenderer.invoke('ai-game-start', prompt),
  getMatchupBrief:  (prompt) => ipcRenderer.invoke('ai-matchup-brief', prompt),
  showCenterNotif:    (msg, pri) => ipcRenderer.send('show-center-notif', { msg, pri }),
  dismissCenterNotif:  ()        => ipcRenderer.send('dismiss-center-notif'),
  saveGameResult:      (data)   => ipcRenderer.invoke('save-game-result', data),
  loadSessionHistory:  ()       => ipcRenderer.invoke('load-session-history'),
  loadAlertSettings:   ()       => ipcRenderer.invoke('load-alert-settings'),
  saveAlertSettings:   (mutes)  => ipcRenderer.invoke('save-alert-settings', mutes),
  getVersion:          ()       => ipcRenderer.invoke('get-version'),
  showPostGame:        (data)   => ipcRenderer.send('show-post-game', data),
  openBattleLog:       ()       => ipcRenderer.send('open-battle-log'),
  toggleBattleLog:     ()       => ipcRenderer.send('toggle-battle-log'),
  openAiSetup:         ()       => ipcRenderer.send('open-ai-setup'),
  toggleAiSetup:       ()       => ipcRenderer.send('toggle-ai-setup'),
  toggleInfoWindow:    ()       => ipcRenderer.send('toggle-info-window'),
  onAiKeySaved:        (cb)     => ipcRenderer.on('ai-key-saved', () => cb()),
  openUrl:             (url)    => ipcRenderer.send('open-url', url),
  getScoutContext:     ()       => ipcRenderer.invoke('get-scout-context'),
  getChampKit:         ()       => ipcRenderer.invoke('get-champ-kit'),
  onFinalEvents:       (cb)    => ipcRenderer.on('final-events', (_, data) => cb(data)),
  toggleDashboard:     ()       => ipcRenderer.send('toggle-dashboard'),
  sendDashboardUpdate: (payload) => ipcRenderer.send('dashboard-update', payload),
})
